### ISSUE TITLE
please a release for delete invoices, thanks

### ISSUE THREAD

**Issue by bitkarrot** [lnbits/invoices#2]

**Comment by dni** [comment]
it is? https://github.com/lnbits/lnbits-extensions/pull/84

**Comment by dni** [comment]
i see somehow gh, did not createa a release, only a tag :confused:

**Comment by dni** [comment]
found it. https://github.com/lnbits/invoices/commit/ead9e1bb1c0809c46e11951dd964c8bb669895b2

**Comment by bitkarrot** [comment]
Thank you ! <3
